// <auto-generated />
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026120739_seedingCouponsData")]
    partial class seedingCouponsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.CouponModel", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "DISCOUNT10",
                            DiscountAmount = 10.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "SAVE15",
                            DiscountAmount = 15.0,
                            MinAmount = 150
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "SPRING20",
                            DiscountAmount = 20.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "SUMMER25",
                            DiscountAmount = 25.0,
                            MinAmount = 250
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "FALL30",
                            DiscountAmount = 30.0,
                            MinAmount = 300
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "WINTER35",
                            DiscountAmount = 35.0,
                            MinAmount = 350
                        },
                        new
                        {
                            CouponId = 7,
                            CouponCode = "NEWYEAR40",
                            DiscountAmount = 40.0,
                            MinAmount = 400
                        },
                        new
                        {
                            CouponId = 8,
                            CouponCode = "HOLIDAY45",
                            DiscountAmount = 45.0,
                            MinAmount = 450
                        },
                        new
                        {
                            CouponId = 9,
                            CouponCode = "FLASH50",
                            DiscountAmount = 50.0,
                            MinAmount = 500
                        },
                        new
                        {
                            CouponId = 10,
                            CouponCode = "SUPER55",
                            DiscountAmount = 55.0,
                            MinAmount = 550
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
